export * from './email';
export * from './max';
export * from './maxlength';
export * from './min';
export * from './minlength';
export * from './pattern';
export * from './pattern-base';
export * from './patterns';
export * from './required';
